query NeuroFetalMrSeries($StudyInstanceUID: String!, $pacs_id: bigint!) {
  pacsfile(
    distinct_on: SeriesInstanceUID
    where: {
      _and: [
        { Modality: { _eq: "MR" } }
        { SeriesDescription: { _ilike: "%T2%" } }
        { SeriesDescription: { _iregex: "(cervix)|(uterus)|(HASTE)" } }
        { StudyInstanceUID: { _eq: $StudyInstanceUID } }
        { pacs_id: { _eq: $pacs_id } }
      ]
    }
  ) {
    SeriesDescription
    fname
  }
}
